#!/usr/bin/env bash
# Common utilities and DRY_RUN support for mirroret.
# Source this file; do not execute it directly.
# Requires logging.sh to be sourced first.

# -- DRY_RUN support ----------------------------------------------------------
# Set DRY_RUN=1 (or pass --dry-run) to prevent any system modifications.
# The run() wrapper below honours this flag.
DRY_RUN="${DRY_RUN:-0}"

# run <cmd> [args...] - execute a command unless DRY_RUN is active.
xrun() {
    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would run: $*"
        return 0
    fi
    debug "running: $*"
    "$@"
}

# run_quietly <cmd> - run but suppress stdout/stderr (still logs on failure).
run_quietly() {
    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would run: $*"
        return 0
    fi
    debug "running quietly: $*"
    # A fixed /tmp path is a symlink-race target when running as root.
    local out
    out="$(mktemp /tmp/mirroret_cmd_out.XXXXXX)" || return 1
    if ! "$@" > "$out" 2>&1; then
        error "command failed: $*"
        cat "$out" >&2
        rm -f "$out"
        return 1
    fi
    rm -f "$out"
}

# write_file <path> <content> - write content to a file (respects DRY_RUN).
# Use a here-string or process substitution for multi-line content.
write_file() {
    local path="$1"
    local content="$2"
    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write to: ${path}"
        return 0
    fi
    printf '%s\n' "$content" > "$path"
}

# -- Root/privilege checks -----------------------------------------------------

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        die "This script must be run as root (sudo $0 $*)."
    fi
}

# -- Command existence checks -------------------------------------------------

require_command() {
    local cmd="$1"
    if ! command -v "$cmd" &>/dev/null; then
        die "Required command not found: ${cmd}. Install it and try again."
    fi
}

# check_command <cmd> - returns 0 if present, 1 if missing (non-fatal).
check_command() {
    command -v "$1" &>/dev/null
}

# -- Atomic file writes -------------------------------------------------------

# atomic_write <dest> <tmpfile> - move tmpfile to dest only after validation.
# Use this to avoid leaving a broken config on disk if generation fails.
atomic_write() {
    local dest="$1"
    local tmp="$2"
    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would move ${tmp} -> ${dest}"
        return 0
    fi
    mv "$tmp" "$dest"
}

# -- Upgrade-safe overwrite (MIRRORET-MANAGED sentinel) -----------------------
#
# All generated scripts under /srv/mirroret/scripts/ include this marker
# line near the top:
#
# # MIRRORET-MANAGED: regenerated by install.sh. To customize the
# # package list, use MIRRORET_*_PACKAGES_FILE (see docs/CONFIGURATION.md).
#
# When install.sh runs a second time, is_managed_file() checks whether
# an existing target still contains the sentinel. If it does, the operator
# hasn't edited it and we're safe to regenerate. If it doesn't, the
# operator has replaced or heavily customized the file and we preserve it.
MIRRORET_MANAGED_MARKER="# MIRRORET-MANAGED: regenerated by install.sh"

# -- Generated-script runtime preamble ----------------------------------------
# Every generated sync/cleanup script must start with this. cron and systemd
# hand a script a MINIMAL environment - no /etc/environment, no shell rc, no
# proxy vars. Without this preamble every nightly sync fails on any host
# behind a proxy, while manual `sudo -E` runs succeed, which is a
# maddening class of bug to debug.
#
# Emits: conf sourcing, proxy export, CA bundle export.
mirroret_script_preamble() {
    cat <<'PREAMBLE'
# -- Runtime environment --------------------------------------------------
# cron/systemd give this script a minimal env. Load operator config and
# re-export proxy + CA settings so upstream fetches work unattended.
if [[ -f /etc/mirroret/mirroret.conf ]]; then
    # shellcheck disable=SC1091
    . /etc/mirroret/mirroret.conf
fi
# MIRRORET_PROXY is the single operator-facing knob (the wizard writes it).
# Every tool underneath - python urllib, curl, pip, npm, dnf - reads the
# conventional http_proxy/https_proxy names, so map it onto those when they
# are not already set. Without this line the proxy answer was recorded and
# never used, and every unattended sync behind a corporate proxy failed.
if [[ -n "${MIRRORET_PROXY:-}" ]]; then
    : "${http_proxy:=${MIRRORET_PROXY}}"
    : "${https_proxy:=${MIRRORET_PROXY}}"
fi
if [[ -n "${MIRRORET_NO_PROXY:-}" ]]; then
    : "${no_proxy:=${MIRRORET_NO_PROXY}}"
fi
# Loopback must never go through the corporate proxy: the npm sync talks to
# Verdaccio on localhost:4873, approvals publish to it, and nginx proxies to
# the cache daemon on 127.0.0.1. With a proxy set and no bypass, every one of
# those was sent to the proxy and failed.
if [[ -n "${http_proxy:-}${https_proxy:-}" ]]; then
    case ",${no_proxy:-}," in
        *,localhost,*|*,127.0.0.1,*) ;;
        *) no_proxy="${no_proxy:+${no_proxy},}localhost,127.0.0.1,::1" ;;
    esac
fi
for _v in http_proxy https_proxy no_proxy HTTP_PROXY HTTPS_PROXY NO_PROXY; do
    [[ -n "${!_v:-}" ]] && export "${_v}"
done
# Mirror lowercase<->uppercase so every tool sees the proxy.
[[ -z "${https_proxy:-}" && -n "${HTTPS_PROXY:-}" ]] && export https_proxy="${HTTPS_PROXY}"
[[ -z "${HTTPS_PROXY:-}" && -n "${https_proxy:-}" ]] && export HTTPS_PROXY="${https_proxy}"
[[ -z "${http_proxy:-}" && -n "${HTTP_PROXY:-}" ]] && export http_proxy="${HTTP_PROXY}"
[[ -z "${HTTP_PROXY:-}" && -n "${http_proxy:-}" ]] && export HTTP_PROXY="${http_proxy}"
[[ -z "${no_proxy:-}" && -n "${NO_PROXY:-}" ]] && export no_proxy="${NO_PROXY}"
[[ -z "${NO_PROXY:-}" && -n "${no_proxy:-}" ]] && export NO_PROXY="${no_proxy}"
# Corporate CA bundle - pip/requests/node each need telling separately.
if [[ -n "${MIRRORET_CA_BUNDLE:-}" && -f "${MIRRORET_CA_BUNDLE}" ]]; then
    export SSL_CERT_FILE="${MIRRORET_CA_BUNDLE}"
    export REQUESTS_CA_BUNDLE="${MIRRORET_CA_BUNDLE}"
    export PIP_CERT="${MIRRORET_CA_BUNDLE}"
    export NODE_EXTRA_CA_CERTS="${MIRRORET_CA_BUNDLE}"
    export CURL_CA_BUNDLE="${MIRRORET_CA_BUNDLE}"
fi
PREAMBLE
}

# is_managed_file <path> - true if <path> does not exist OR contains the
# managed marker (i.e. safe for install.sh to overwrite).
is_managed_file() {
    local path="$1"
    [[ ! -e "$path" ]] && return 0
    grep -qF "${MIRRORET_MANAGED_MARKER}" "$path" 2>/dev/null
}

# preserve_user_customization <path> - if the file exists but has lost the
# managed marker, log a preservation notice and return 1 (caller should skip
# regeneration). Otherwise return 0.
preserve_user_customization() {
    local path="$1"
    if [[ ! -e "$path" ]]; then
        return 0
    fi
    if is_managed_file "$path"; then
        return 0
    fi
    warn "Preserving your customized ${path}"
    warn " (managed marker missing - mirroret will not overwrite user edits)"
    warn " Restore mirroret's default by deleting the file, then re-running install.sh."
    return 1
}

# -- Idempotency helpers ------------------------------------------------------

# file_contains <file> <pattern> - true if file exists and contains the pattern.
file_contains() {
    local file="$1"
    local pattern="$2"
    [[ -f "$file" ]] && grep -qF "$pattern" "$file"
}

# service_is_active <name> - true if a systemd service is active.
service_is_active() {
    systemctl is-active --quiet "$1" 2>/dev/null
}

# service_is_enabled <name> - true if a systemd service is enabled.
service_is_enabled() {
    systemctl is-enabled --quiet "$1" 2>/dev/null
}

# container_exists <name> - true if a Docker container exists (any state).
container_exists() {
    docker ps -a --format '{{.Names}}' 2>/dev/null | grep -qx "$1"
}

# container_is_running <name> - true if a Docker container is running.
container_is_running() {
    docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$1"
}

# -- Temporary file helpers ---------------------------------------------------

# mktemp_file - create a temp file and print its path.
mktemp_file() {
    mktemp /tmp/mirroret.XXXXXX
}

# -- Target spec helpers ------------------------------------------------------

# mirroret_json_field <file> <field> - print one top-level value from a JSON
# target spec, or nothing. Lists are joined with spaces.
#
# python3 is already a hard requirement for the mirroring engines, so this
# avoids inventing a JSON parser in bash (and avoids the grep-based
# "parsers" that break the first time a value contains a brace).
mirroret_json_field() {
    local file="$1" field="$2"
    [[ -f "${file}" ]] || return 0
    python3 - "${file}" "${field}" <<'MIRRORET_JSON_PY' 2>/dev/null || true
import json
import sys

try:
    with open(sys.argv[1]) as fh:
        data = json.load(fh)
except (OSError, ValueError):
    sys.exit(1)
value = data.get(sys.argv[2], "")
if isinstance(value, list):
    parts = []
    for item in value:
        if isinstance(item, dict):
            # Lists of objects (suites, repos): print their id/suite key.
            parts.append(str(item.get("suite") or item.get("id") or ""))
        else:
            parts.append(str(item))
    print(" ".join(p for p in parts if p))
elif isinstance(value, bool):
    print("1" if value else "0")
else:
    print(value)
MIRRORET_JSON_PY
}

# -- Misc ---------------------------------------------------------------------

# get_server_ip - return the primary non-loopback IPv4 address.
# Can be overridden by setting MIRRORET_SERVER_IP.
#
# Strategy (each step skipped silently on failure / empty output):
# 1. MIRRORET_SERVER_IP override
# 2. Address used to reach the default gateway (works air-gapped: a
# default route only needs to exist, not actually go to the internet)
# 3. First non-loopback, non-link-local global-scope IPv4 address on
# any interface (no route required)
# 4. Legacy `hostname -I` first field
# 5. Loud, actionable error
get_server_ip() {
    if [[ -n "${MIRRORET_SERVER_IP:-}" ]]; then
        echo "$MIRRORET_SERVER_IP"
        return 0
    fi

    local ip=""

    if check_command ip; then
        # Step 2: route via the default gateway. Does not require Internet.
        local gw
        gw="$(ip -4 route show default 2>/dev/null | awk '/default/ {print $3; exit}')"
        if [[ -n "$gw" ]]; then
            ip="$(ip -4 route get "$gw" 2>/dev/null | awk '/src/ {for (i=1;i<=NF;i++) if ($i=="src") {print $(i+1); exit}}')"
        fi

        # Step 3: first global-scope IPv4 on any interface.
        if [[ -z "$ip" ]]; then
            ip="$(ip -4 -o addr show scope global 2>/dev/null \
                | awk '{print $4}' | head -1 | cut -d/ -f1)"
        fi
    fi

    # Step 4: legacy fallback.
    if [[ -z "$ip" ]] && check_command hostname; then
        ip="$(hostname -I 2>/dev/null | awk '{print $1}')"
    fi

    if [[ -z "$ip" ]]; then
        error "Could not determine the server's IPv4 address."
        error "Set MIRRORET_SERVER_IP explicitly, e.g.:"
        error " sudo MIRRORET_SERVER_IP=192.168.1.10 ./install.sh"
        return 1
    fi

    echo "$ip"
}

# confirm <prompt> - ask the user y/n; returns 0 for yes, 1 for no.
# In non-interactive mode (MIRRORET_NON_INTERACTIVE=1), defaults to no.
confirm() {
    local prompt="${1:-Continue?}"
    if [[ "${MIRRORET_NON_INTERACTIVE:-0}" == "1" ]]; then
        warn "Non-interactive mode: auto-declining: ${prompt}"
        return 1
    fi
    read -r -p "${prompt} [y/N] " reply
    [[ "${reply}" =~ ^[Yy]$ ]]
}

# confirm_yes <prompt> - like confirm but defaults to yes in non-interactive.
confirm_yes() {
    local prompt="${1:-Continue?}"
    if [[ "${MIRRORET_NON_INTERACTIVE:-0}" == "1" ]]; then
        debug "Non-interactive mode: auto-confirming: ${prompt}"
        return 0
    fi
    read -r -p "${prompt} [Y/n] " reply
    [[ -z "$reply" || "${reply}" =~ ^[Yy]$ ]]
}
