#!/usr/bin/env bash
# nginx configuration management for mirroret.
# Source this file; do not execute it directly.
# Requires logging.sh, common.sh, backup.sh.

# configure_nginx_basic <backup_id> — write nginx config for APT/RPM-only setup.
configure_nginx_basic() {
    local backup_id="$1"
    local base_dir="${MIRRORET_BASE_DIR}"
    local web_port="${MIRRORET_WEB_PORT:-8080}"

    section "Configuring nginx (basic)"

    _write_nginx_config "$backup_id" "$base_dir" "$web_port" \
        "$(cat <<NGINX_EOF

    # APT/RPM repository browser
    location /mirror {
        alias ${base_dir}/mirror;
        autoindex on;
    }

    location /approved {
        alias ${base_dir}/approved;
        autoindex on;
    }

    location /config {
        alias ${base_dir}/config;
        autoindex on;
    }
NGINX_EOF
    )" "mirroret"
}

# configure_nginx_unified <backup_id> — write nginx config for the unified setup.
configure_nginx_unified() {
    local backup_id="$1"
    local base_dir="${MIRRORET_BASE_DIR}"
    local web_port="${MIRRORET_WEB_PORT:-8080}"
    local pip_port="${MIRRORET_PIP_PORT:-8081}"
    local npm_port="${MIRRORET_NPM_PORT:-4873}"
    local docker_port="${MIRRORET_DOCKER_REGISTRY_PORT:-5000}"

    section "Configuring nginx (unified)"

    _write_nginx_config "$backup_id" "$base_dir" "$web_port" \
        "$(cat <<NGINX_EOF

    # APT mirror — apt-mirror writes to mirror/mirror/archive.ubuntu.com/ubuntu/
    # Clients use: deb http://server:PORT/ubuntu codename main
    location /ubuntu {
        alias ${base_dir}/debian/mirror/mirror/archive.ubuntu.com/ubuntu;
        autoindex on;
    }

    # RPM mirror — reposync writes to redhat/mirror/rocky/VER/REPO/
    # Clients use: baseurl=http://server:PORT/redhat/rocky/VER/baseos
    location /redhat {
        alias ${base_dir}/redhat/mirror;
        autoindex on;
    }

    location /config {
        alias ${base_dir}/config;
        autoindex on;
    }

    # PyPI proxy (pypiserver on ${pip_port})
    location /pip/ {
        proxy_pass http://127.0.0.1:${pip_port}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 300s;
    }

    # npm proxy (Verdaccio on ${npm_port})
    location /npm/ {
        proxy_pass http://127.0.0.1:${npm_port}/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 300s;
    }

    # Docker registry proxy (on ${docker_port})
    location /v2/ {
        proxy_pass http://127.0.0.1:${docker_port}/v2/;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        client_max_body_size 0;
        chunked_transfer_encoding on;
        proxy_read_timeout 900s;
    }
NGINX_EOF
    )" "mirroret-unified"
}

# ── Internal helpers ─────────────────────────────────────────────────────────

_write_nginx_config() {
    local backup_id="$1"
    local base_dir="$2"
    local web_port="$3"
    local extra_locations="$4"
    local config_name="$5"

    local conf_file
    local sites_enabled_symlink=""

    if [[ -d /etc/nginx/sites-available ]]; then
        # Debian/Ubuntu style
        conf_file="/etc/nginx/sites-available/${config_name}"
        sites_enabled_symlink="/etc/nginx/sites-enabled/${config_name}"
    else
        # RHEL style
        conf_file="/etc/nginx/conf.d/${config_name}.conf"
    fi

    # Back up existing config.
    backup_file "$backup_id" "$conf_file"
    [[ -n "$sites_enabled_symlink" ]] && backup_file "$backup_id" "$sites_enabled_symlink"

    # Write to a temp file first for safe validation.
    local tmpfile
    tmpfile="$(mktemp_file)"

    cat > "$tmpfile" <<NGINX_CONF
# Generated by mirroret — do not edit manually.
server {
    listen ${web_port};
    server_name _;

    root ${base_dir};
    autoindex on;

    location / {
        try_files \$uri \$uri/ =404;
    }
${extra_locations}

    # Allow large packages.
    client_max_body_size 0;

    access_log /var/log/nginx/${config_name}-access.log;
    error_log  /var/log/nginx/${config_name}-error.log;
}
NGINX_CONF

    # Validate before placing on disk.
    if ! _validate_nginx_tmpconfig "$tmpfile"; then
        rm -f "$tmpfile"
        die "nginx config validation failed. Aborting to protect existing config."
    fi

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write nginx config to: ${conf_file}"
        rm -f "$tmpfile"
        return 0
    fi

    atomic_write "$conf_file" "$tmpfile"
    info "nginx config written: ${conf_file}"

    # Enable the site on Debian/Ubuntu.
    if [[ -n "$sites_enabled_symlink" ]]; then
        ln -sf "$conf_file" "$sites_enabled_symlink"
        info "Site enabled: ${sites_enabled_symlink}"
    fi

    # Remove default site to avoid port conflicts.
    _remove_default_site

    # Test the final config.
    if ! nginx -t 2>/dev/null; then
        error "nginx config test failed after writing. Rolling back."
        rollback "$backup_id"
        die "nginx configuration failed."
    fi

    xrun systemctl enable nginx
    xrun systemctl reload nginx 2>/dev/null || xrun systemctl restart nginx
    success "nginx configured and (re)loaded on port ${web_port}."
}

_validate_nginx_tmpconfig() {
    local tmpfile="$1"
    if ! check_command nginx; then
        debug "nginx not installed yet; skipping pre-write validation."
        return 0
    fi
    # nginx -t -c requires a full nginx.conf, not just a server block.
    # Wrap the server block in minimal http{} boilerplate so nginx can parse it.
    local wrapper
    wrapper="$(mktemp_file)"
    printf 'events {}\nhttp { include %s; }\n' "$tmpfile" > "$wrapper"
    local rc=0
    nginx -t -c "$wrapper" 2>/dev/null || rc=$?
    rm -f "$wrapper"
    return $rc
}

_remove_default_site() {
    # Remove the default nginx site to avoid conflicts on port 80/8080.
    local defaults=(
        "/etc/nginx/sites-enabled/default"
        "/etc/nginx/conf.d/default.conf"
    )
    for f in "${defaults[@]}"; do
        if [[ -f "$f" ]] || [[ -L "$f" ]]; then
            info "Removing default nginx site: ${f}"
            xrun rm -f "$f"
        fi
    done
}

# reload_nginx — reload or restart nginx safely.
reload_nginx() {
    if service_is_active nginx; then
        nginx -t &>/dev/null && xrun systemctl reload nginx || xrun systemctl restart nginx
    else
        xrun systemctl start nginx
    fi
}
