#!/usr/bin/env bash
# Verdaccio npm registry setup for mirroret.
# Source this file; do not execute it directly.
# Requires logging.sh, common.sh, backup.sh, systemd.sh.

MIRRORET_NPM_USER="${MIRRORET_NPM_USER:-mirroret-npm}"

# setup_npm_registry <backup_id> — install Verdaccio and create systemd unit.
setup_npm_registry() {
    local backup_id="$1"
    local base_dir="${MIRRORET_BASE_DIR}"
    local npm_port="${MIRRORET_NPM_PORT:-4873}"

    section "Setting Up npm Registry (Verdaccio)"

    _ensure_npm_user
    _install_verdaccio
    _write_verdaccio_config "$backup_id" "$base_dir"
    _write_verdaccio_unit "$backup_id" "$base_dir" "$npm_port"
    systemd_daemon_reload
    enable_and_start verdaccio
    _write_npm_sync_script "$base_dir"

    success "Verdaccio configured on port ${npm_port}."
}

_ensure_npm_user() {
    if ! id "${MIRRORET_NPM_USER}" &>/dev/null; then
        if [[ "${DRY_RUN}" == "1" ]]; then
            info "[DRY-RUN] would create system user: ${MIRRORET_NPM_USER}"
            return 0
        fi
        xrun useradd --system --no-create-home --shell /usr/sbin/nologin "${MIRRORET_NPM_USER}"
        info "Created system user: ${MIRRORET_NPM_USER}"
    else
        debug "System user already exists: ${MIRRORET_NPM_USER}"
    fi
}

_install_verdaccio() {
    if check_command verdaccio; then
        info "Verdaccio already installed."
        return 0
    fi

    require_command npm
    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would run: npm install -g verdaccio"
        return 0
    fi
    xrun npm install -g verdaccio
    info "Verdaccio installed."
}

_write_verdaccio_config() {
    local backup_id="$1"
    local base_dir="$2"

    backup_file "$backup_id" "/etc/verdaccio/config.yaml"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write Verdaccio config to /etc/verdaccio/config.yaml"
        return 0
    fi

    mkdir -p /etc/verdaccio
    # Create an empty htpasswd file so Verdaccio starts cleanly.
    touch /etc/verdaccio/htpasswd

    cat > /etc/verdaccio/config.yaml <<VERD_EOF
# Verdaccio configuration — generated by mirroret.
storage: ${base_dir}/npm/approved
plugins: /usr/lib/verdaccio/plugins

auth:
  htpasswd:
    file: /etc/verdaccio/htpasswd
    max_users: 1000

uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 30s
    maxage: 10m

packages:
  '@*/*':
    access: \$all
    publish: \$authenticated
    unpublish: \$authenticated
    proxy: npmjs
  '**':
    access: \$all
    publish: \$authenticated
    unpublish: \$authenticated
    proxy: npmjs

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

logs:
  - { type: stdout, format: pretty, level: warn }
VERD_EOF

    chown -R "${MIRRORET_NPM_USER}:" /etc/verdaccio
    success "Verdaccio config written."
}

_write_verdaccio_unit() {
    local backup_id="$1"
    local base_dir="$2"
    local npm_port="$3"

    local verdaccio_bin
    verdaccio_bin="$(command -v verdaccio 2>/dev/null || echo /usr/bin/verdaccio)"

    local unit_content="[Unit]
Description=Verdaccio npm Registry (mirroret)
After=network.target

[Service]
Type=simple
User=${MIRRORET_NPM_USER}
ExecStart=${verdaccio_bin} --config /etc/verdaccio/config.yaml --listen ${npm_port}
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=${base_dir}/npm /etc/verdaccio
PrivateTmp=true

[Install]
WantedBy=multi-user.target"

    write_systemd_unit "$backup_id" "verdaccio.service" "$unit_content"

    if [[ "${DRY_RUN}" != "1" ]]; then
        xrun chown -R "${MIRRORET_NPM_USER}:" "${base_dir}/npm"
    fi
}

_write_npm_sync_script() {
    local base_dir="$1"
    local sync_script="${base_dir}/scripts/sync-npm-packages.sh"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write npm sync script: ${sync_script}"
        return 0
    fi

    mkdir -p "${base_dir}/scripts"

    cat > "$sync_script" <<'SYNC_EOF'
#!/usr/bin/env bash
set -Eeuo pipefail

# npm package sync script for mirroret.
# Downloads package tarballs from npmjs.org into a staging directory,
# then publishes them to the local Verdaccio registry.
# Edit PACKAGES to control what is mirrored.

STAGING_DIR="BASE_DIR/npm/staging"
LOG_DIR="BASE_DIR/logs"
LOG_FILE="${LOG_DIR}/sync-npm-$(date +%Y%m%d-%H%M%S).log"
mkdir -p "$LOG_DIR" "$STAGING_DIR"

echo "Starting npm package sync: $(date)" | tee -a "$LOG_FILE"

PACKAGES=(
    "express"
    "lodash"
    "axios"
    "react"
    "webpack"
    "typescript"
    "eslint"
)

failed=0
cd "$STAGING_DIR"

for package in "${PACKAGES[@]}"; do
    echo "Downloading ${package}..." | tee -a "$LOG_FILE"
    # npm pack downloads the tarball without installing dependencies.
    if npm pack "$package" 2>&1 | tee -a "$LOG_FILE"; then
        echo "  OK: ${package}" | tee -a "$LOG_FILE"
    else
        echo "  FAILED: ${package}" | tee -a "$LOG_FILE"
        (( failed += 1 )) || true
    fi
done

echo "npm sync completed: $(date) (${failed} failures)" | tee -a "$LOG_FILE"
echo "Tarballs are in: ${STAGING_DIR}"
echo "To publish to local registry, run:"
echo "  cd ${STAGING_DIR} && for f in *.tgz; do npm publish \$f --registry http://localhost:4873/; done"
exit "${failed}"
SYNC_EOF

    sed -i "s|BASE_DIR|${base_dir}|g" "$sync_script"
    chmod +x "$sync_script"
    success "npm sync script written: ${sync_script}"
}

# generate_npm_client_config <output_file> — write .npmrc for clients.
generate_npm_client_config() {
    local output_file="$1"
    local server_ip="${MIRRORET_SERVER_IP}"
    local npm_port="${MIRRORET_NPM_PORT:-4873}"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write npm client config to: ${output_file}"
        return 0
    fi

    cat > "$output_file" <<NPM_EOF
registry=http://${server_ip}:${npm_port}/
NPM_EOF

    success "npm client config written: ${output_file}"
}
