#!/usr/bin/env bash
# pypiserver setup for mirroret.
# Source this file; do not execute it directly.
# Requires logging.sh, common.sh, backup.sh, systemd.sh.

MIRRORET_PYPI_USER="${MIRRORET_PYPI_USER:-mirroret-pip}"

# setup_pip_repository <backup_id> — install pypiserver and create systemd unit.
setup_pip_repository() {
    local backup_id="$1"
    local base_dir="${MIRRORET_BASE_DIR}"
    local pip_port="${MIRRORET_PIP_PORT:-8081}"

    section "Setting Up pip Repository (pypiserver)"

    _ensure_pypi_user
    _install_pypiserver
    _write_pypiserver_unit "$backup_id" "$base_dir" "$pip_port"
    systemd_daemon_reload
    enable_and_start pypiserver
    _write_pip_sync_script "$base_dir"

    success "pypiserver configured on port ${pip_port}."
}

_ensure_pypi_user() {
    if ! id "${MIRRORET_PYPI_USER}" &>/dev/null; then
        if [[ "${DRY_RUN}" == "1" ]]; then
            info "[DRY-RUN] would create system user: ${MIRRORET_PYPI_USER}"
            return 0
        fi
        xrun useradd --system --no-create-home --shell /usr/sbin/nologin "${MIRRORET_PYPI_USER}"
        info "Created system user: ${MIRRORET_PYPI_USER}"
    else
        debug "System user already exists: ${MIRRORET_PYPI_USER}"
    fi
}

_install_pypiserver() {
    if check_command pypi-server; then
        info "pypiserver already installed."
        return 0
    fi

    # Prefer the distro package; fall back to pip in a venv.
    if [[ "${DISTRO_TYPE}" == "debian" ]]; then
        if apt-cache show python3-pypiserver &>/dev/null 2>&1; then
            xrun apt-get install -y --no-install-recommends python3-pypiserver
            return 0
        fi
    fi

    # Fall back: install into a dedicated virtualenv to avoid --break-system-packages.
    local venv_dir="/opt/mirroret-pypiserver"
    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would install pypiserver into venv: ${venv_dir}"
        return 0
    fi
    xrun python3 -m venv "$venv_dir"
    xrun "${venv_dir}/bin/pip" install --quiet pypiserver passlib
    # Create a wrapper in PATH.
    ln -sf "${venv_dir}/bin/pypi-server" /usr/local/bin/pypi-server
    info "pypiserver installed in virtualenv: ${venv_dir}"
}

_write_pypiserver_unit() {
    local backup_id="$1"
    local base_dir="$2"
    local pip_port="$3"

    local pypi_bin
    pypi_bin="$(command -v pypi-server 2>/dev/null || echo /usr/local/bin/pypi-server)"

    # Serve approved/ (standard) or approved/ under the approval workflow root.
    # Both point to the same semantics; approval.sh promotes staging → approved.
    local serve_dir="${base_dir}/pip/approved"
    if [[ "${MIRRORET_APPROVAL_ENABLED:-0}" == "1" ]]; then
        serve_dir="${base_dir}/approved/pip"
        mkdir -p "${base_dir}/staging/pip" "${base_dir}/approved/pip"
    fi

    local unit_content="[Unit]
Description=PyPI Server (mirroret)
After=network.target

[Service]
Type=simple
User=${MIRRORET_PYPI_USER}
WorkingDirectory=${base_dir}/pip
ExecStart=${pypi_bin} run -p ${pip_port} --overwrite ${serve_dir}
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=${base_dir}/pip ${base_dir}/staging ${base_dir}/approved
PrivateTmp=true

[Install]
WantedBy=multi-user.target"

    write_systemd_unit "$backup_id" "pypiserver.service" "$unit_content"

    # Set correct ownership.
    if [[ "${DRY_RUN}" != "1" ]]; then
        xrun chown -R "${MIRRORET_PYPI_USER}:" "${base_dir}/pip"
    fi
}

_write_pip_sync_script() {
    local base_dir="$1"
    local sync_script="${base_dir}/scripts/sync-pip-packages.sh"
    local approval="${MIRRORET_APPROVAL_ENABLED:-0}"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write pip sync script: ${sync_script}"
        return 0
    fi

    mkdir -p "${base_dir}/scripts"

    # Destination depends on approval mode.
    local dest_dir
    if [[ "${approval}" == "1" ]]; then
        dest_dir="${base_dir}/staging/pip"
    else
        dest_dir="${base_dir}/pip/approved"
    fi

    cat > "${sync_script}" <<PIP_SYNC
#!/usr/bin/env bash
set -Eeuo pipefail

# pip package sync script — generated by mirroret.
# Downloads packages from PyPI. Edit PACKAGES to control what is mirrored.

DEST_DIR="${dest_dir}"
LOG_DIR="${base_dir}/logs"
LOG_FILE="\${LOG_DIR}/sync-pip-\$(date +%Y%m%d-%H%M%S).log"
APPROVAL_MODE="${approval}"
mkdir -p "\$LOG_DIR" "\$DEST_DIR"

echo "Starting pip package sync: \$(date)" | tee -a "\$LOG_FILE"

PACKAGES=(
    "requests"
    "flask"
    "django"
    "numpy"
    "pandas"
    "pytest"
    "black"
    "pylint"
    "ansible"
    "boto3"
    "setuptools"
    "wheel"
)

failed=0
for package in "\${PACKAGES[@]}"; do
    echo "Downloading \${package}..." | tee -a "\$LOG_FILE"
    if pip3 download "\${package}" -d "\${DEST_DIR}" 2>&1 | tee -a "\$LOG_FILE"; then
        echo "  OK: \${package}" | tee -a "\$LOG_FILE"
    else
        echo "  FAILED: \${package}" | tee -a "\$LOG_FILE"
        (( failed += 1 )) || true
    fi
done

echo "pip sync completed: \$(date) (\${failed} failures)" | tee -a "\$LOG_FILE"
if [[ "\${APPROVAL_MODE}" == "1" ]]; then
    echo "Packages in staging: \${DEST_DIR}" | tee -a "\$LOG_FILE"
    echo "Approve with: mirroret --approve-all-pip" | tee -a "\$LOG_FILE"
fi
exit "\${failed}"
PIP_SYNC

    chmod +x "${sync_script}"
    success "pip sync script written: ${sync_script}"
}

# generate_pip_client_config <output_file> — write pip.conf for clients.
generate_pip_client_config() {
    local output_file="$1"
    local server_ip="${MIRRORET_SERVER_IP}"
    local pip_port="${MIRRORET_PIP_PORT:-8081}"
    local insecure="${MIRRORET_PIP_INSECURE:-0}"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write pip client config to: ${output_file}"
        return 0
    fi

    if [[ "${insecure}" == "1" ]]; then
        warn_insecure "pip client config: trusted-host set (certificate checking DISABLED)."
        warn_insecure "This is suitable for isolated lab environments ONLY."

        cat > "$output_file" <<PIP_EOF
[global]
index-url = http://${server_ip}:${pip_port}/simple/
trusted-host = ${server_ip}
PIP_EOF

    else
        # pypiserver serves plain HTTP by default. Use http:// unless TLS is
        # explicitly configured on the server via a reverse proxy.
        # Set MIRRORET_PIP_INSECURE=1 to suppress this note in lab mode.
        cat > "$output_file" <<PIP_EOF
[global]
index-url = http://${server_ip}:${pip_port}/simple/
PIP_EOF
        info "pip client config written (http). For TLS, front pypiserver with an nginx TLS proxy."
        info "See docs/SECURITY.md for TLS setup."
    fi

    success "pip client config written: ${output_file}"
}
