#!/usr/bin/env bash
# RPM repository configuration for mirroret.
# Source this file; do not execute it directly.
# Requires logging.sh, common.sh, distro.sh, backup.sh.

# configure_createrepo <backup_id> — write the RHEL/CentOS sync script.
configure_createrepo() {
    local backup_id="$1"
    local base_dir="${MIRRORET_BASE_DIR}"
    local rhel_ver
    rhel_ver="${MIRRORET_RHEL_VERSION:-$(rhel_major_version)}"

    section "Configuring createrepo (RHEL-based)"
    info "RHEL major version: ${rhel_ver}"

    local sync_script="${base_dir}/scripts/sync-redhat-repos.sh"
    backup_file "$backup_id" "$sync_script"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write: ${sync_script}"
        return 0
    fi

    mkdir -p "${base_dir}/scripts"

    cat > "$sync_script" <<SYNC_EOF
#!/usr/bin/env bash
set -Eeuo pipefail

REPO_BASE="${base_dir}/redhat/mirror"
LOG_DIR="${base_dir}/logs"
LOG_FILE="\${LOG_DIR}/sync-redhat-\$(date +%Y%m%d-%H%M%S).log"
mkdir -p "\$LOG_DIR"

echo "Starting RHEL repository sync: \$(date)" | tee -a "\$LOG_FILE"

RHEL_VER="${rhel_ver}"
REPOS=(baseos appstream extras)

for repo in "\${REPOS[@]}"; do
    mkdir -p "\${REPO_BASE}/rocky/\${RHEL_VER}/\${repo}"
    reposync -p "\${REPO_BASE}/rocky/\${RHEL_VER}" \\
        --download-metadata \\
        --repo "\${repo}" 2>&1 | tee -a "\$LOG_FILE" || \\
        echo "WARNING: reposync failed for \${repo}" | tee -a "\$LOG_FILE"
done

for repo in "\${REPOS[@]}"; do
    local_path="\${REPO_BASE}/rocky/\${RHEL_VER}/\${repo}"
    if [ -d "\$local_path" ]; then
        createrepo --update "\$local_path" 2>&1 | tee -a "\$LOG_FILE"
    fi
done

echo "RHEL sync completed: \$(date)" | tee -a "\$LOG_FILE"
SYNC_EOF

    chmod +x "$sync_script"
    success "RHEL sync script written: ${sync_script}"
}

# generate_rpm_client_config <output_file> — write a .repo file for clients.
generate_rpm_client_config() {
    local output_file="$1"
    local server_ip="${MIRRORET_SERVER_IP}"
    local web_port="${MIRRORET_WEB_PORT:-8080}"
    local rhel_ver
    rhel_ver="${MIRRORET_RHEL_VERSION:-$(rhel_major_version)}"
    local insecure="${MIRRORET_RPM_INSECURE:-0}"

    section "Generating RPM client config"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would write RPM client config to: ${output_file}"
        return 0
    fi

    local gpg_check_line gpg_key_line
    if [[ "${insecure}" == "1" ]]; then
        warn_insecure "RPM client config generated with gpgcheck=0 (GPG checking DISABLED)."
        warn_insecure "This is suitable for isolated lab environments ONLY."
        warn_insecure "Set MIRRORET_RPM_INSECURE=0 and configure a GPG key for production use."
        gpg_check_line="gpgcheck=0"
        gpg_key_line=""
    elif [[ -n "${MIRRORET_RPM_GPGKEY_URL:-}" ]]; then
        gpg_check_line="gpgcheck=1"
        gpg_key_line="gpgkey=${MIRRORET_RPM_GPGKEY_URL}"
    else
        # Default to gpgcheck=1 with a placeholder.
        gpg_check_line="gpgcheck=1"
        gpg_key_line="# gpgkey=http://${server_ip}:${web_port}/RPM-GPG-KEY-mirroret"
        warn "RPM client config: gpgcheck=1 but no MIRRORET_RPM_GPGKEY_URL set."
        warn "Clients will fail to verify packages until a gpgkey is configured."
        warn "See docs/SECURITY.md for GPG key setup."
    fi

    cat > "$output_file" <<REPO_EOF
# Local Repository Server - RHEL/CentOS/Rocky
# Generated by mirroret. Place in /etc/yum.repos.d/ on clients.

[mirroret-baseos]
name=Mirroret - BaseOS
baseurl=http://${server_ip}:${web_port}/redhat/rocky/${rhel_ver}/baseos
enabled=1
${gpg_check_line}
${gpg_key_line}

[mirroret-appstream]
name=Mirroret - AppStream
baseurl=http://${server_ip}:${web_port}/redhat/rocky/${rhel_ver}/appstream
enabled=1
${gpg_check_line}
${gpg_key_line}

[mirroret-extras]
name=Mirroret - Extras
baseurl=http://${server_ip}:${web_port}/redhat/rocky/${rhel_ver}/extras
enabled=1
${gpg_check_line}
${gpg_key_line}
REPO_EOF

    success "RPM client config written: ${output_file}"
}
