#!/usr/bin/env bash
# TLS certificate management for mirroret.
# Source this file; do not execute it directly.
# Requires logging.sh, common.sh.
#
# Variables (set in config or on the command line):
#   MIRRORET_TLS_SELF_SIGNED=1    generate a self-signed cert on install
#   MIRRORET_TLS_CERT=<path>      path to an existing PEM certificate
#   MIRRORET_TLS_KEY=<path>       path to the matching private key
#   MIRRORET_TLS_PORT=8443        port for the nginx HTTPS listener
#   MIRRORET_TLS_DIR=/etc/mirroret/tls   directory for generated cert files

MIRRORET_TLS_ENABLED="${MIRRORET_TLS_ENABLED:-0}"
MIRRORET_TLS_SELF_SIGNED="${MIRRORET_TLS_SELF_SIGNED:-0}"
MIRRORET_TLS_CERT="${MIRRORET_TLS_CERT:-}"
MIRRORET_TLS_KEY="${MIRRORET_TLS_KEY:-}"
MIRRORET_TLS_PORT="${MIRRORET_TLS_PORT:-8443}"
MIRRORET_TLS_DIR="${MIRRORET_TLS_DIR:-/etc/mirroret/tls}"

# setup_tls — provision or validate a TLS certificate and key.
# Sets MIRRORET_TLS_CERT, MIRRORET_TLS_KEY, and MIRRORET_TLS_ENABLED=1.
setup_tls() {
    section "Setting Up TLS"

    if [[ "${MIRRORET_TLS_SELF_SIGNED}" == "1" ]]; then
        _tls_generate_self_signed
    elif [[ -n "${MIRRORET_TLS_CERT}" && -n "${MIRRORET_TLS_KEY}" ]]; then
        _tls_validate_existing
    else
        die "TLS requested but no cert/key provided. Set MIRRORET_TLS_CERT+KEY or MIRRORET_TLS_SELF_SIGNED=1."
    fi

    MIRRORET_TLS_ENABLED=1
    export MIRRORET_TLS_CERT MIRRORET_TLS_KEY MIRRORET_TLS_ENABLED MIRRORET_TLS_PORT
    success "TLS ready — cert: ${MIRRORET_TLS_CERT}  port: ${MIRRORET_TLS_PORT}"
}

_tls_generate_self_signed() {
    local cert_file="${MIRRORET_TLS_DIR}/cert.pem"
    local key_file="${MIRRORET_TLS_DIR}/key.pem"
    local server_ip="${MIRRORET_SERVER_IP:-localhost}"

    if [[ "${DRY_RUN}" == "1" ]]; then
        info "[DRY-RUN] would generate self-signed cert in ${MIRRORET_TLS_DIR}"
        MIRRORET_TLS_CERT="${cert_file}"
        MIRRORET_TLS_KEY="${key_file}"
        return 0
    fi

    require_command openssl

    mkdir -p "${MIRRORET_TLS_DIR}"
    chmod 750 "${MIRRORET_TLS_DIR}"

    if [[ -f "${cert_file}" && -f "${key_file}" ]]; then
        info "Self-signed cert already exists — re-using: ${cert_file}"
        MIRRORET_TLS_CERT="${cert_file}"
        MIRRORET_TLS_KEY="${key_file}"
        return 0
    fi

    info "Generating 4096-bit self-signed certificate for ${server_ip} (valid 10 yr)."
    openssl req -x509 -newkey rsa:4096 \
        -keyout "${key_file}" -out "${cert_file}" \
        -days 3650 -nodes \
        -subj "/CN=${server_ip}/O=mirroret" \
        -addext "subjectAltName=IP:${server_ip},DNS:${server_ip}" \
        2>/dev/null

    chmod 640 "${cert_file}"
    chmod 600 "${key_file}"
    MIRRORET_TLS_CERT="${cert_file}"
    MIRRORET_TLS_KEY="${key_file}"

    warn_insecure "Self-signed certificate generated."
    warn_insecure "Clients will see an untrusted-CA warning until they import ${cert_file}."
    warn_insecure "See docs/SECURITY.md for CA trust and production cert procedures."
}

_tls_validate_existing() {
    [[ -f "${MIRRORET_TLS_CERT}" ]] || die "TLS cert not found: ${MIRRORET_TLS_CERT}"
    [[ -f "${MIRRORET_TLS_KEY}" ]]  || die "TLS key not found: ${MIRRORET_TLS_KEY}"
    require_command openssl
    openssl x509 -noout -in "${MIRRORET_TLS_CERT}" 2>/dev/null \
        || die "Cannot parse TLS certificate: ${MIRRORET_TLS_CERT}"
    info "TLS cert validated: ${MIRRORET_TLS_CERT}"
}

# is_tls_ready — true when TLS cert+key are in place.
is_tls_ready() {
    [[ "${MIRRORET_TLS_ENABLED:-0}" == "1" ]] \
        && [[ -n "${MIRRORET_TLS_CERT:-}" ]] \
        && [[ -n "${MIRRORET_TLS_KEY:-}" ]]
}

# tls_nginx_server_block <extra_locations> <config_name>
# Emit an nginx server block that listens on MIRRORET_TLS_PORT with SSL.
tls_nginx_server_block() {
    local extra_locations="${1:-}"
    local config_name="${2:-mirroret-unified}"
    local tls_port="${MIRRORET_TLS_PORT:-8443}"
    local base_dir="${MIRRORET_BASE_DIR}"

    cat <<TLS_BLOCK

# ── TLS listener — generated by mirroret ─────────────────────────────────────
server {
    listen ${tls_port} ssl http2;
    server_name _;

    ssl_certificate     ${MIRRORET_TLS_CERT};
    ssl_certificate_key ${MIRRORET_TLS_KEY};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    root ${base_dir};
    autoindex on;

    location / {
        try_files \$uri \$uri/ =404;
    }
${extra_locations}

    client_max_body_size 0;
    access_log /var/log/nginx/${config_name}-tls-access.log;
    error_log  /var/log/nginx/${config_name}-tls-error.log;
}
TLS_BLOCK
}
