#!/usr/bin/env bash
# lib/wizard.sh - interactive first-run configuration.
#
# When the operator runs `sudo ./install.sh` on a fresh box with nothing
# preconfigured (no /etc/mirroret/mirroret.conf, no MIRRORET_APT_TARGETS
# in env, no --yes), walk them through the setup: what to mirror, which
# arches, proxy, disk floor. Sensible defaults so pressing Enter picks a
# working configuration.
#
# The wizard writes /etc/mirroret/mirroret.conf itself (so the choices
# survive re-runs), and exports the MIRRORET_* variables the rest of the
# installer already reads.

# ANSI colour helpers, degrading to no-colour on a dumb terminal.
if [[ -t 1 && "${TERM:-dumb}" != "dumb" ]]; then
    _WZ_BOLD=$'\033[1m'; _WZ_DIM=$'\033[2m'
    _WZ_GRN=$'\033[32m'; _WZ_YEL=$'\033[33m'
    _WZ_CYA=$'\033[36m'; _WZ_RED=$'\033[31m'
    _WZ_END=$'\033[0m'
else
    _WZ_BOLD=""; _WZ_DIM=""; _WZ_GRN=""; _WZ_YEL=""; _WZ_CYA=""; _WZ_RED=""; _WZ_END=""
fi

_wz_header() {
    printf '\n%s%s%s\n' "${_WZ_BOLD}${_WZ_CYA}" "$1" "${_WZ_END}"
    printf '%s\n' "${_WZ_DIM}${1//?/-}${_WZ_END}"
}

_wz_prompt() {
    # $1 = prompt text, $2 = default (may be empty), sets REPLY
    local prompt="$1" default="${2:-}" hint="" reply
    [[ -n "$default" ]] && hint=" ${_WZ_DIM}[$default]${_WZ_END}"
    printf '  %s%s: ' "$prompt" "$hint" >&2
    IFS= read -r reply
    REPLY="${reply:-$default}"
}

_wz_yesno() {
    # $1 = prompt, $2 = default y|n
    local prompt="$1" default="${2:-y}" hint reply
    if [[ "$default" == "y" ]]; then hint="[Y/n]"; else hint="[y/N]"; fi
    printf '  %s %s%s%s ' "$prompt" "${_WZ_DIM}" "$hint" "${_WZ_END}" >&2
    IFS= read -r reply
    reply="${reply:-$default}"
    [[ "$reply" =~ ^[Yy]$ ]]
}

_wz_menu() {
    # $1 = heading, then <key>|<label> pairs
    local heading="$1"; shift
    printf '\n  %s%s%s\n' "${_WZ_BOLD}" "$heading" "${_WZ_END}" >&2
    local i=1 pair key label
    _WZ_MENU_KEYS=()
    for pair in "$@"; do
        key="${pair%%|*}"; label="${pair#*|}"
        _WZ_MENU_KEYS+=("$key")
        printf '    %s%d)%s %s\n' "${_WZ_YEL}" "$i" "${_WZ_END}" "$label" >&2
        i=$((i+1))
    done
}

_wz_multichoice() {
    # $1 = prompt, $2 = default indices (like "1 2"), then labels.
    # Sets REPLY to space-separated selected keys.
    local prompt="$1" default_idx="$2"; shift 2
    _wz_menu "$prompt" "$@"
    printf '  %s(space-separated numbers; default %s)%s: ' \
        "${_WZ_DIM}" "$default_idx" "${_WZ_END}" >&2
    local raw
    IFS= read -r raw
    raw="${raw:-$default_idx}"
    local out=() n
    for n in $raw; do
        [[ "$n" =~ ^[0-9]+$ ]] || continue
        if (( n >= 1 && n <= ${#_WZ_MENU_KEYS[@]} )); then
            out+=("${_WZ_MENU_KEYS[$((n-1))]}")
        fi
    done
    REPLY="${out[*]}"
}

# _wz_write_conf <path> - materialise the answers to a config file.
_wz_write_conf() {
    local conf="$1"
    mkdir -p "$(dirname "$conf")"
    # Write a leading marker so /etc/mirroret/mirroret.conf.example can be
    # kept alongside without confusion.
    cat > "$conf" <<EOF
# mirroret configuration - generated by the interactive wizard.
# Re-run 'sudo ./install.sh' and answer the prompts again to change these,
# or edit this file and 'sudo ./install.sh --upgrade' to apply.

# --- what to mirror --------------------------------------------------------
MIRRORET_APT_TARGETS="${MIRRORET_APT_TARGETS}"
MIRRORET_RPM_TARGETS="${MIRRORET_RPM_TARGETS}"

# --- which ecosystems to serve ---------------------------------------------
MIRRORET_ENABLE_APT="${MIRRORET_ENABLE_APT:-1}"
MIRRORET_ENABLE_RPM="${MIRRORET_ENABLE_RPM:-1}"
MIRRORET_ENABLE_PIP="${MIRRORET_ENABLE_PIP:-1}"
MIRRORET_ENABLE_NPM="${MIRRORET_ENABLE_NPM:-1}"
MIRRORET_ENABLE_DOCKER="${MIRRORET_ENABLE_DOCKER:-1}"

# --- how to mirror ---------------------------------------------------------
# mirror = everything up front | hybrid = indices up front, packages on
# demand | cache = everything on demand. See docs/CACHE.md.
MIRRORET_APT_MODE="${MIRRORET_APT_MODE:-mirror}"
MIRRORET_CACHE_MAX_SIZE_GB="${MIRRORET_CACHE_MAX_SIZE_GB:-0}"

# --- upstream network ------------------------------------------------------
${_wz_proxy_line}
${_wz_apt_scheme_line}

# --- disk safety -----------------------------------------------------------
MIRRORET_SYNC_MIN_FREE_GB="${MIRRORET_SYNC_MIN_FREE_GB:-15}"

# --- sync scheduling -------------------------------------------------------
MIRRORET_SYNC_HOUR="${MIRRORET_SYNC_HOUR:-2}"
EOF
    chmod 0644 "$conf"
}

# run_first_run_wizard - the entry point install.sh calls.
run_first_run_wizard() {
    printf '\n'
    printf '%s%s╭──────────────────────────────────────────────╮%s\n' "${_WZ_BOLD}" "${_WZ_CYA}" "${_WZ_END}"
    printf '%s%s│         mirroret first-run wizard            │%s\n' "${_WZ_BOLD}" "${_WZ_CYA}" "${_WZ_END}"
    printf '%s%s╰──────────────────────────────────────────────╯%s\n' "${_WZ_BOLD}" "${_WZ_CYA}" "${_WZ_END}"
    printf '\n%s%s%s\n\n' "${_WZ_DIM}" \
        "Press Enter to accept each default. Ctrl-C to abort." "${_WZ_END}"

    # 1. APT flavours ------------------------------------------------------
    _wz_multichoice "Which APT distros should this mirror serve?" "1" \
        "ubuntu:noble|Ubuntu 24.04 Noble Numbat  (LTS, current)" \
        "ubuntu:jammy|Ubuntu 22.04 Jammy Jellyfish (LTS)" \
        "ubuntu:focal|Ubuntu 20.04 Focal Fossa (LTS, older)" \
        "debian:bookworm|Debian 12 Bookworm (current stable)" \
        "debian:bullseye|Debian 11 Bullseye (oldstable)" \
        "none|None (no APT clients)"
    local apt_targets="$REPLY"

    # Prune the "none" sentinel if it was chosen.
    if [[ " $apt_targets " == *" none "* ]]; then
        apt_targets=""
    fi

    # 1b. Mirroring strategy ------------------------------------------------
    # Asked before architectures because it changes the disk answer by two
    # orders of magnitude, which is usually the deciding constraint.
    export MIRRORET_APT_MODE="mirror"
    export MIRRORET_CACHE_MAX_SIZE_GB="0"
    if [[ -n "$apt_targets" ]]; then
        local free_gb="unknown"
        if command -v df >/dev/null 2>&1; then
            free_gb="$(df -BG --output=avail /srv 2>/dev/null | tail -1 \
                       | tr -dc '0-9')" || free_gb=""
            [[ -z "$free_gb" ]] && free_gb="unknown"
        fi
        printf '\n  %sDisk available under /srv: %s GB%s\n' \
            "${_WZ_DIM}" "${free_gb}" "${_WZ_END}"
        printf '  %sA full Ubuntu mirror (one release, amd64) is roughly 400 GB.%s\n' \
            "${_WZ_DIM}" "${_WZ_END}"
        _wz_multichoice "How should packages be stored?" "2" \
            "mirror|Full mirror   - every package up front. Fully offline. Hundreds of GB." \
            "hybrid|Hybrid (recommended) - indices up front (~2 GB), packages fetched on first use and kept." \
            "cache|Pure cache   - nothing up front; indices and packages both on demand. Smallest."
        local mode="${REPLY%% *}"     # multichoice returns a list; take the first
        case "$mode" in
            mirror|hybrid|cache) export MIRRORET_APT_MODE="$mode" ;;
            *)                   export MIRRORET_APT_MODE="hybrid" ;;
        esac

        if [[ "${MIRRORET_APT_MODE}" != "mirror" ]]; then
            _wz_prompt \
                "Cap the package cache at how many GB? (0 = no cap, keep everything)" \
                "0"
            export MIRRORET_CACHE_MAX_SIZE_GB="$REPLY"
        fi
    fi

    local apt_arches=""
    if [[ -n "$apt_targets" ]]; then
        _wz_multichoice \
            "Which APT architectures? (amd64 covers most; add i386 for legacy Wine/Steam)" \
            "1" \
            "amd64|amd64 (64-bit x86)" \
            "i386|i386 (32-bit x86, legacy)" \
            "arm64|arm64 (aarch64)"
        apt_arches="$REPLY"
        [[ -z "$apt_arches" ]] && apt_arches="amd64"
        # Attach the arch list to every target: ubuntu:noble becomes
        # ubuntu:noble:amd64,i386. lib/targets.sh already parses that.
        local out=() t
        local joined
        joined="${apt_arches// /,}"
        for t in $apt_targets; do
            out+=("${t}:${joined}")
        done
        apt_targets="${out[*]}"
    fi

    # 2. RPM flavours ------------------------------------------------------
    _wz_multichoice \
        "Which RPM distros should this mirror serve?" \
        "6" \
        "ol:9|Oracle Linux 9 (baseos + appstream)" \
        "ol:8|Oracle Linux 8" \
        "rocky:9|Rocky Linux 9" \
        "rocky:8|Rocky Linux 8" \
        "epel:9|EPEL 9 (extra packages)" \
        "none|None (no RPM clients)"
    local rpm_targets="$REPLY"
    if [[ " $rpm_targets " == *" none "* ]]; then
        rpm_targets=""
    fi

    # 3. Other ecosystems ---------------------------------------------------
    # These used to install unconditionally, so answering "None" to both APT
    # and RPM still stood up pypiserver, Verdaccio and a registry that nobody
    # asked for.
    _wz_multichoice \
        "Which other package ecosystems should this server provide?" \
        "" \
        "pip|Python packages (pypiserver on :8081)" \
        "npm|Node packages (Verdaccio on :4873)" \
        "docker|Container images (registry on :5000, pull-through cache)"
    local extras="$REPLY"
    _wz_want() { if [[ " $extras " == *" $1 "* ]]; then echo 1; else echo 0; fi; }
    local want_pip want_npm want_docker
    want_pip="$(_wz_want pip)"
    want_npm="$(_wz_want npm)"
    want_docker="$(_wz_want docker)"
    export MIRRORET_ENABLE_PIP="$want_pip"
    export MIRRORET_ENABLE_NPM="$want_npm"
    export MIRRORET_ENABLE_DOCKER="$want_docker"

    # Picking "None" for a distro family must actually disable that family,
    # not just leave it with an empty target list to warn about later.
    if [[ -n "$apt_targets" ]]; then
        export MIRRORET_ENABLE_APT=1
    else
        export MIRRORET_ENABLE_APT=0
    fi
    if [[ -n "$rpm_targets" ]]; then
        export MIRRORET_ENABLE_RPM=1
    else
        export MIRRORET_ENABLE_RPM=0
    fi

    # 4. Proxy -------------------------------------------------------------
    export MIRRORET_APT_TARGETS="$apt_targets"
    export MIRRORET_RPM_TARGETS="$rpm_targets"
    _wz_proxy_line=""
    _wz_apt_scheme_line='MIRRORET_APT_SCHEME="http"'
    if _wz_yesno "Do outbound requests go through a corporate proxy?" "n"; then
        _wz_prompt "Proxy URL (e.g. http://proxy.example:3128)" ""
        local proxy="$REPLY"
        if [[ -n "$proxy" ]]; then
            _wz_proxy_line="MIRRORET_PROXY=\"${proxy}\""
            export MIRRORET_PROXY="$proxy"
            # Corporate CONNECT-only proxies won't relay plain HTTP to
            # Ubuntu; force HTTPS so it round-trips as CONNECT :443.
            if _wz_yesno \
                "Force HTTPS to upstream (recommended for CONNECT-only proxies)?" "y"
            then
                _wz_apt_scheme_line='MIRRORET_APT_SCHEME="https"'
                export MIRRORET_APT_SCHEME="https"
            fi
        fi
    fi

    # 5. Disk floor --------------------------------------------------------
    _wz_prompt "Refuse to start a sync when free disk would drop below (GB)" "15"
    export MIRRORET_SYNC_MIN_FREE_GB="$REPLY"

    # 6. Confirmation & write -----------------------------------------------
    local enabled=""
    [[ "${MIRRORET_ENABLE_PIP}" == "1" ]] && enabled="${enabled} pip"
    [[ "${MIRRORET_ENABLE_NPM}" == "1" ]] && enabled="${enabled} npm"
    [[ "${MIRRORET_ENABLE_DOCKER}" == "1" ]] && enabled="${enabled} docker"

    _wz_header "Summary"
    printf '    APT targets : %s%s%s\n' "${_WZ_GRN}" "${apt_targets:-<none>}" "${_WZ_END}"
    printf '    RPM targets : %s%s%s\n' "${_WZ_GRN}" "${rpm_targets:-<none>}" "${_WZ_END}"
    printf '    storage mode: %s%s%s\n' "${_WZ_GRN}" "${MIRRORET_APT_MODE}" "${_WZ_END}"
    if [[ "${MIRRORET_APT_MODE}" != "mirror" ]]; then
        printf '    cache cap   : %s%s%s\n' "${_WZ_GRN}" \
            "$([[ "${MIRRORET_CACHE_MAX_SIZE_GB}" == "0" ]] \
               && echo "no cap" || echo "${MIRRORET_CACHE_MAX_SIZE_GB} GB")" \
            "${_WZ_END}"
    fi
    printf '    also serving: %s%s%s\n' "${_WZ_GRN}" "${enabled:- <none>}" "${_WZ_END}"
    printf '    proxy       : %s%s%s\n' "${_WZ_GRN}" "${MIRRORET_PROXY:-<none>}" "${_WZ_END}"
    printf '    APT scheme  : %s%s%s\n' "${_WZ_GRN}" "${MIRRORET_APT_SCHEME:-http}" "${_WZ_END}"
    printf '    disk floor  : %s%s%s GB\n' \
        "${_WZ_GRN}" "${MIRRORET_SYNC_MIN_FREE_GB}" "${_WZ_END}"
    printf '\n'
    if ! _wz_yesno "Write this to /etc/mirroret/mirroret.conf and continue?" "y"; then
        printf '%sAborted.%s\n' "${_WZ_YEL}" "${_WZ_END}" >&2
        exit 130
    fi
    _wz_write_conf /etc/mirroret/mirroret.conf
    printf '  %s✓ wrote /etc/mirroret/mirroret.conf%s\n\n' \
        "${_WZ_GRN}" "${_WZ_END}"
}

# should_run_first_run_wizard - true when nothing is preconfigured and
# stdin is a real TTY. Called from install.sh's main().
should_run_first_run_wizard() {
    # Never in --upgrade, --yes / non-interactive, or when the config is
    # already there.
    [[ "${MODE_UPGRADE:-0}" == "1" ]] && return 1
    [[ "${MIRRORET_NON_INTERACTIVE:-0}" == "1" ]] && return 1
    [[ "${DRY_RUN:-0}" == "1" ]] && return 1
    [[ -t 0 ]] || return 1
    [[ -f /etc/mirroret/mirroret.conf ]] && return 1
    [[ -n "${MIRRORET_APT_TARGETS}${MIRRORET_RPM_TARGETS}" ]] && return 1
    return 0
}
